config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :questions do
    member do
      post :vote
      post :subscribe_update
      post :subscribe_new_answer
      patch :unsubscribe_update
      patch :unsubscribe_new_answer
    end
    collection { delete :cancel_vote }

    resources :answers, except: :index do
      member do
        patch :set_best
        post :vote
      end

      collection { delete :cancel_vote }
    end
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create] do
        resources :answers, only: %i[index show create]
      end
    end
  end

  delete 'attachments/destroy'

  root 'questions#index'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  validates :title, :body, presence: true
  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :votes, as: :votesable, dependent: :destroy
  has_many :subscriptions
  belongs_to :user

  accepts_nested_attributes_for :attachments

  after_create :reputation_calculate, :create_author_subscription
  after_update :send_update_digest

  scope :ordered, -> { order('updated_at DESC') }

  def likes
    votes.where(vote: :like).count
  end

  def dislikes
    votes.where(vote: :dislike).count
  end

  private

  def create_author_subscription
    subscription = Subscription.new(user: user, question: self, new_answer: true)
    subscription.save!
  end

  def reputation_calculate
    Reputation.calculate(self)
  end

  def send_update_digest
    subscriptions.where(update_question: true).each do |sb|
      UpdateDigestJob.perform_later(sb.user, self)
    end
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class QuestionsController < Api::V1::BaseController
      before_action :find_user, only: :create

      def index
        respond_with(@questions = Question.all)
      end

      def show
        respond_with(@question = Question.find(params[:id]))
      end

      def create
        respond_with(@question = @user.questions.create({ title: params[:title], body: params[:body] }))
      end

      private

      def find_user
        query = "select resource_owner_id from oauth_access_grants where token = '#{params[:code]}'"
        user_id = ActiveRecord::Base.connection.execute(query).first['resource_owner_id']
        @user = User.find(user_id)
      end
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, except: %i[index new create cancel_vote]
  before_action :authorize_question!
  after_action :verify_authorized

  def index
    @pagy, @questions = pagy Question.all.ordered, link_extra: 'data-turbo-frame="pagination"'
  end

  def show
    @pagy, @answers = pagy @question.answers
  end

  def new
    @question = current_user.questions.new
    @question.attachments.build
  end

  def edit
    @question.attachments.build
  end

  def create
    @question = current_user.questions.build question_params
    flash[:notice] = 'Question successfully created!' if @question.save
  end

  def update
    flash[:notice] = 'Question successfully updated!' if @question.update(question_params)
  end

  def destroy
    flash[:notice] = 'Question successfully deleted!' if @question.destroy
  end

  def vote
    if current_user.voted?(:Question)
      flash[:alert] = 'You already voted!'
    else
      flash[:notice] = 'You successfully voted!'
      @question.votes.create vote_params
    end
    @questions = Question.all
  end

  def cancel_vote
    @vote = current_user.votes.where(votesable_type: :Question).first
    flash[:notice] = 'You vote successfully canceled!'
    @vote.destroy
    @questions = Question.all
  end

  def subscribe_update
    if Subscription.where(user: current_user, question: @question).any?
      @sb = Subscription.where(user: current_user, question: @question).first
      @sb.update_question = true
    else
      @sb = Subscription.new(user: current_user, question: @question, update_question: true)
    end
    redirect_to @question, notice: 'You successfully subscribed from updating question!' if @sb.save
  end

  def unsubscribe_update
    @sb = Subscription.where(user: current_user, question: @question).first
    @sb.update_question = false
    redirect_to @question, notice: 'You successfully unsubscribed from updating question!' if @sb.save
  end

  def subscribe_new_answer
    if Subscription.where(user: current_user, question: @question).any?
      @sb = Subscription.where(user: current_user, question: @question).first
      @sb.new_answer = true
    else
      @sb = Subscription.new(user: current_user, question: @question, new_answer: true)
    end
    redirect_to @question, notice: 'You successfully subscribed from updating question!' if @sb.save
  end

  def unsubscribe_new_answer
    @sb = Subscription.where(user: current_user, question: @question).first
    @sb.new_answer = false
    redirect_to @question, notice: 'You successfully unsubscribed from updating question!' if @sb.save
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end

  def vote_params
    params.require(:vote).permit(:user_id, :vote)
  end

  def authorize_question!
    authorize(@question || Question)
  end
end

app/views/questions/_attachment_fields.html.slim
.nested-fields
  .form-floating.w-50.mt-2
    = f.file_field :file
    = link_to_remove_association "remove file", f, class: 'btn btn-secondary btn-sm my-1'

app/views/questions/_create.js.erb
$('.questions').prepend('<%= j render partial: 'questions/question', locals: { question: @question }  %>');
$('.flash').html('<%= j render partial: 'shared/flash' %>');

app/views/questions/_form.html.slim
= form_with model: @question, local: false do |form|
  = render 'shared/errors', object: @question
  .form-floating.w-50.mt-2
    = form.text_field :title, class: 'form-control', id: 'floatingTitle', placeholder: :title
    = form.label :title, for: 'floatingTitle'

  .form-floating.w-50.mt-2
    = form.text_field :body, class: 'form-control', id: 'floatingBody', placeholder: 'Tell about your question'
    = form.label 'Tell about your question', for: 'floatingBody'

  .form-floating.w-50.mt-2
    = form.fields_for :attachments, @question.attachments.build do |task|
      // FIXME: Duplicated link
      .links
        = link_to_add_association 'add task', form, :attachments, class: 'btn btn-secondary btn-sm my-1'

  .form-floating.w-50.mt-2
    = form.submit nil, class: 'btn btn-success my-2'

app/views/questions/_question.html.slim
div class="#{dom_id(question)}"
  .container.border.mb-3
    .row.mb-1
      .col.pt-2
        h5 User: #{question.user.name}
    .row.mb-1
      .col.pt-2
        h3 = question.title
    .row
      .col-12.mb-3
        span.bold = question.body
    .row.mb-1
      .col-4.pt-2
        .votes
          div class="vote-#{dom_id(question)}"
            span = "Likes: #{question.likes}  |  Dislikes: #{question.dislikes}"
    - if question.attachments.present?
      .row.mb-1
        .col-4.pt-2
          .attachments
          h4 Attachments
          table.table.table-hover
            tbody
              - question.attachments.each do |attachment|
                tr class="#{dom_id(attachment)}"
                  td = link_to attachment.file.file.identifier, attachment.file.url
                  td = link_to 'Delete', attachments_destroy_path(attachment_id: attachment),
                          method: :delete, class: 'btn btn-danger btn-sm', remote: true
    .row
      .col
        = link_to 'Show', question_path(question),
                class: 'btn btn-primary me-2'
        - if policy(question).edit?
          = link_to 'Edit', edit_question_path(question), class: 'btn btn-secondary me-2', remote: true
        - if policy(question).destroy?
          = link_to 'Delete', question, class: 'btn btn-danger me-2', method: :delete, remote: true
        -if policy(question).vote?
          =link_to 'Like', vote_question_path(question, vote: {vote: :like, user_id: current_user}),
                  method: :post, remote: true, class: 'btn btn-outline-success me-2'
          = link_to 'Dislike', vote_question_path(question, vote: { vote: :dislike, user_id: current_user }),
                  method: :post, remote: true, class: 'btn btn-outline-danger me-2'
        

app/views/questions/cancel_vote.js.erb
$('.flash').html('<%= j render partial: 'shared/flash' %>');
$('.cancel-vote-button').html('<%=
 if policy(Question).cancel_vote?
  link_to 'Cancel vote', cancel_vote_questions_path, class: 'btn btn-secondary my-2', method: :delete
 end %>');
$('.questions').html('<%= j render partial: 'questions/question', collection: @questions %>')

app/views/questions/create.js.erb
$('.questions').prepend('<%= j render partial: 'questions/question', locals: { question: @question }  %>');
$('.flash').html('<%= j render partial: 'shared/flash' %>');

app/views/questions/destroy.js.erb
$('.<%= dom_id(@question) %>').remove();
$('.flash').html('<%= j render partial: 'shared/flash' %>');

app/views/questions/edit.js.erb
$(".<%= dom_id(@question) %>").html('<%= render partial: 'questions/form' %>')

app/views/questions/index.html.slim
h1 All Questions

.row
  .col class='mb-2'
    .question-form
      = link_to 'Ask something', new_question_path, class: 'btn btn-outline-primary my-2', remote: true
.row
  .col
    .cancel-vote-button
      - if policy(Question).cancel_vote?
        = link_to 'Cancel vote', cancel_vote_questions_path,
                remote: true, method: :delete, class: 'btn btn-secondary my-2'
.row
  .col
    == pagy_bootstrap_nav(@pagy)
    .questions
      = render partial: 'questions/question', collection: @questions
    == pagy_bootstrap_nav(@pagy)

app/views/questions/new.js.erb
$('.question-form').html('<%= j render partial: 'questions/form' %>')

app/views/questions/show.html.slim
h1 = @question.title
span = @question.body
#question-id data-question-id="#{@question.id}"
.row
  .col
    .answer-errors
    .answer_it
      = link_to 'Answer it', new_question_answer_path(@question, @answer), class: 'btn btn-primary m-2', remote: true
.row
  .col
    .cancel-vote-button
      - if policy(@question).answer_cancel_vote?
        = link_to 'Cancel vote', cancel_vote_question_answers_path(@question),
                remote: false, method: :delete, class: 'btn btn-secondary my-2'

.row
  .col
    .subscribe_update_btn
      - if policy(@question).subscribe_update?
        = link_to 'Subscribe to update this question', subscribe_update_question_path(@question),
                remote: true, method: :post, class: 'btn btn-outline-primary my-2'
.row
  .col
    .unsubscribe_update_btn
      - if policy(@question).unsubscribe_update?
        = link_to 'Unsubscribe to update this question', unsubscribe_update_question_path(@question),
                remote: true, method: :patch, class: 'btn btn-outline-danger my-2'

.row
  .col
    .subscribe_update_btn
      - if policy(@question).subscribe_new_answer?
        = link_to 'Subscribe to answer for this question', subscribe_new_answer_question_path(@question),
                remote: true, method: :post, class: 'btn btn-outline-primary my-2'
.row
  .col
    .unsubscribe_update_btn
      - if policy(@question).unsubscribe_new_answer?
        = link_to 'Unsubscribe to answer for this question', unsubscribe_new_answer_question_path(@question),
                remote: true, method: :patch, class: 'btn btn-outline-danger my-2'

.row
  .col
    = link_to 'Back to Questions', questions_path, class: 'btn btn-secondary m-2'

.row
  .col-12
    h3 Answers
    == pagy_bootstrap_nav @pagy
    .answers
      = render partial: 'answers/answer', collection: @answers.order_best, as: :answer, locals: { question: @question }
    == pagy_bootstrap_nav @pagy

app/views/questions/update.js.erb
$('.<%= dom_id(@question) %>').replaceWith('<%= j render partial: 'questions/question', locals: { question: @question } %>');
$('.flash').html('<%= j render partial: 'shared/flash' %>');

app/views/questions/vote.js.erb
$('.flash').html('<%= j render partial: 'shared/flash' %>');
$('.cancel-vote-button').html('<%=
 if policy(Question).cancel_vote?
  link_to 'Cancel vote', cancel_vote_questions_path, class: 'btn btn-secondary my-2', method: :delete, remote: true
 end %>');
$('.questions').html('<%= j render partial: 'questions/question', collection: @questions %>')