config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :questions do
    member do
      post :vote
      post :subscribe_update
      post :subscribe_new_answer
      patch :unsubscribe_update
      patch :unsubscribe_new_answer
    end
    collection { delete :cancel_vote }

    resources :answers, except: :index do
      member do
        patch :set_best
        post :vote
      end

      collection { delete :cancel_vote }
    end
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create] do
        resources :answers, only: %i[index show create]
      end
    end
  end

  delete 'attachments/destroy'

  root 'questions#index'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  validates :body, presence: true
  belongs_to :question
  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :votes, as: :votesable, dependent: :destroy

  accepts_nested_attributes_for :attachments

  scope :order_best, -> { order(best: :desc) }

  after_create :send_new_answer_digest

  def likes
    votes.where(vote: :like).count
  end

  def dislikes
    votes.where(vote: :dislike).count
  end

  def send_new_answer_digest
    question.subscriptions.where(new_answer: true).each do |sb|
      NewAnswerDigestJob.perform_later(sb.user, question)
    end
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_answer, only: %i[edit update destroy set_best vote]
  before_action :find_best_answer, only: :set_best
  before_action :find_question
  before_action :authorize_answer!
  after_action :verify_authorized
  after_action :publish_answer, only: :create

  def new
    @answer = Answer.new
    @answer.attachments.build
  end

  def edit; end

  def create
    @answer = current_user.answers.build(answer_params)
    @answer.question_id = params[:question_id]

    flash[:notice] = 'Answer successfully created!' if @answer.save
  end

  def update
    if @answer.update(answer_params)
      flash[:notice] = 'Answer successfully edited!'
    else
      render :edit
    end
  end

  def set_best
    @best_answer.update(best: false)
    @answer.update(best: true)
    flash[:notice] = 'Best answer successfully selected!'
  end

  def destroy
    flash[:notice] = 'Answer successfully deleted!' if @answer.destroy
  end

  def vote
    if current_user.voted?(:Answer, @question.id)
      flash[:alert] = 'You already voted!'
    else
      flash[:notice] = 'You successfully voted!'
      @answer.votes.create vote_params
    end
  end

  def cancel_vote
    @vote = current_user.votes.where(votesable_type: :Answer, votesable_parent_id: @question.id).first
    flash[:notice] = 'You vote successfully canceled!'
    @vote.destroy
    @questions = Question.all
  end

  private

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "question_channel_#{@question.id}",
      render_answer
    )
  end

  # FIXME: rendering same partial for all users
  def render_answer
    AnswersController.renderer.instance_variable_set(
      :@env, {
        'HTTP_HOST' => 'qna-popovych.herokuapp.com',
        'HTTPS' => 'on',
        'REQUEST_METHOD' => 'GET',
        'SCRIPT_NAME' => '',
        'warden' => warden
      }
    )

    AnswersController.render(
      partial: 'answers/answer',
      locals: { answer: @answer, question: @question }
    )
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def find_best_answer
    @best_answer = Answer.where(best: true)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def vote_params
    params.require(:vote).permit(:user_id, :vote, :votesable_parent_id)
  end

  def answer_params
    params.require(:answer).permit(:body, :user_id, attachments_attributes: [:file])
  end

  def authorize_answer!
    authorize(@answer || Answer)
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AnswersController < Api::V1::BaseController
      before_action :find_question, except: :index

      def index
        respond_with(@answers = @question.answers)
      end

      def show
        respond_with(@answer = @question.answers.find(params[:id]))
      end

      def create
        @answer = @question.answers.create({ body: params[:body], user: @question.user })
        respond_with @question
      end

      private

      def find_question
        @question = Question.find(params[:question_id])
      end
    end
  end
end

app/views/answers/_answer.html.slim
div class="#{dom_id(answer)}"
  .container.border.mb-3
    - if answer.best?
      .row.mb-1
        .col.pt-2
          span.fw-bolder Best Answer
          svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" style="width: 25px; color: blue;"
            path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371\
                               1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1\
                                1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98\
                                 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
    .row.mb-1
      .col.pt-2
        span = "User: #{answer.user.name}"
    .row.mb-1
      .col.pt-2
        span = answer.body
    .row.mb-1
      .col-4.pt-2
        .votes
          div class="vote-#{dom_id(answer)}"
            span = "Likes: #{answer.likes}  |  Dislikes: #{answer.dislikes}"
    - if answer.attachments.present?
      .row.mb-1
        .col-4.pt-2
          .attachments
          h4 Attachments
          table.table.table-hover
            tbody
              - answer.attachments.each do |attachment|
                tr class="#{dom_id(attachment)}"
                  td = link_to attachment.file.file.identifier, attachment.file.url
                  td = link_to 'Delete', attachments_destroy_path(attachment_id: attachment),
                          method: :delete, class: 'btn btn-danger btn-sm', remote: true
    .row.mb-1
      .col
        - if policy(answer).edit?
          = link_to 'Edit', edit_question_answer_path(question, answer),
                  class: 'btn btn-secondary',
                  remote: true
        - if policy(answer).destroy?
          = link_to "Delete", question_answer_path(question, answer), class: 'btn btn-danger m-2', method: :delete, remote: true
        - if policy(answer).set_best? and !answer.best?
          = link_to 'Set best', set_best_question_answer_path(question, answer),
                  class: 'btn btn-outline-primary me-2',
                  method: :patch, remote: true
        -if policy(answer).vote?
          =link_to 'Like', vote_question_answer_path(question, answer,
                  vote: {vote: :like, user_id: current_user, votesable_parent_id: question.id}),
                  method: :post, remote: true, class: 'btn btn-outline-success me-2'
          = link_to 'Dislike', vote_question_answer_path(question, answer, vote: { vote: :dislike, user_id: current_user }),
                  method: :post, remote: true, class: 'btn btn-outline-danger my-2'

app/views/answers/_attachment_fields.html.slim
.nested-fields
  .form-floating.w-50.mt-2
    = f.file_field :file
    = link_to_remove_association "remove file", f, class: 'btn btn-secondary btn-sm my-1'

app/views/answers/_create.js.erb
var error_block = $('.answer-errors')
<% if @answer.errors.present? %>
  error_block.html("<% @answer.errors.full_messages.each do |message| %> <div class='alert alert-danger'>  <%= j message %> </div> <% end %>");
<% else %>
  error_block.html('');
  $('.flash').html('<%= j render partial: 'shared/flash' %>');
  $(".answers").prepend('<%= j render partial: 'answers/answer', locals: { answer: @answer } %>');

<%end %>

app/views/answers/_form.html.slim
= form_with model: [@question, @answer], local: false do |form|
  .form-floating.mt-2
    = form.text_field :body, class: "form-control", id: "floatingBody", placeholder: "Answer"
    = form.label "Answer", for: "floatingBody"

  .form-floating.w-50.mt-2
    = form.fields_for :attachments do |task|
      // FIXME: Duplicated link
      .links
        = link_to_add_association 'add task', form, :attachments, class: 'btn btn-secondary btn-sm my-1'

  .form-floating.w-50.mt-2
    = form.submit nil, class: "btn btn-success mb-2"

app/views/answers/cancel_vote.js.erb
$('.flash').html('<%= j render partial: 'shared/flash' %>');
$('.cancel-vote-button').html('<%=
 if policy(Question).cancel_vote?
  link_to 'Cancel vote', cancel_vote_questions_path, class: 'btn btn-secondary my-2', method: :delete
 end %>');
$('.answers').html('<%= j render partial: 'answers/answer', collection: @question.answers.order_best %>')

app/views/answers/create.js.erb
var error_block = $('.answer-errors')
<% if @answer.errors.present? %>
  error_block.html("<% @answer.errors.full_messages.each do |message| %> <div class='alert alert-danger'>  <%= j message %> </div> <% end %>");
<% else %>
  error_block.html('');
  $('.flash').html('<%= j render partial: 'shared/flash' %>');
  $(".answers").prepend('<%= j render partial: 'answers/answer', locals: { answer: @answer } %>');

<%end %>

app/views/answers/destroy.js.erb
$(".<%= dom_id(@answer) %>").remove()
$('.flash').html('<%= j render partial: 'shared/flash' %>')

app/views/answers/edit.js.erb
$(".<%= dom_id(@answer) %>").html('<%= render partial: 'answers/form' %>')

app/views/answers/new.js.erb
$('.answer_it').html('<%= j render partial: 'answers/form' %>')

app/views/answers/set_best.js.erb
<% @question.answers.each do |answer| %>
  $('.<%= dom_id(answer) %>').replaceWith('<%= j render partial: 'answers/answer', locals: {answer: answer} %>');
<% end %>
$('.<%= dom_id(@answer) %>').remove();
$('.answers').prepend('<%= j render partial: 'answers/answer', locals: {answer: @answer} %>');
$('.flash').html('<%= j render partial: 'shared/flash' %>');

app/views/answers/update.js.erb
var error_block = $('.answer-errors')
<% if @answer.errors.present? %>
  error_block.html("<% @answer.errors.full_messages.each do |message| %> <div class='alert alert-danger'>  <%= j message %> </div> <% end %>");
<% else %>
  error_block.html('');
  $('.flash').html('<%= j render partial: 'shared/flash' %>')
  $(".<%= dom_id(@answer) %>").replaceWith('<%= j render partial: 'answers/answer', locals: { answer: @answer } %>');
<% end %>

app/views/answers/vote.js.erb
$('.flash').html('<%= j render partial: 'shared/flash' %>');
$('.cancel-vote-button').html('<%=
 if policy(@question).answer_cancel_vote?
  link_to 'Cancel vote', cancel_vote_question_answers_path(@question),
   class: 'btn btn-secondary my-2', method: :delete, remote: true
 end %>');
$('.answers').html('<%= j render partial: 'answers/answer', collection: @question.answers.order_best %>')